name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: server_config

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/docker/web

            if [ -d "BACKEND" ]; then
              echo "Directory exists. Pulling latest changes."
              cd BACKEND
              git reset --hard
              git clean -fd
              git checkout DEPLOY
              git pull origin DEPLOY
            else
              echo "Directory does not exist. Cloning repository."
              git clone --branch DEPLOY https://github.com/Y0rFa1se/BACKEND.git
              cd BACKEND
            fi

            echo "${{ secrets.DOT_ENV }}" > .env

            if [ -n "$(docker ps -q -f "name=backend-1")" ]; then
              docker build -t backend-2 .
              echo "backend-1 exists"
              docker run -d --restart=always --name backend-2 -v web:/app/web -p 8004:8001 backend-2

              while ! curl -s http://192.168.0.18:8004; do
                sleep 5
              done

              docker stop backend-1 || true
              docker rm backend-1 || true
              docker rmi backend-1 || true

            elif [ -n "$(docker ps -q -f "name=backend-2")" ]; then
              docker build -t backend-1 .
              echo "backend-2 exists"
              docker run -d --restart=always --name backend-1 -v web:/app/web -p 8003:8001 backend-1

              while ! curl -s http://192.168.0.18:8003; do
                sleep 5
              done

            else
              docker build -t backend-1 .
              echo "Neither exists"
              docker run -d --restart=always --name backend-1 -v web:/app/web -p 8003:8001 backend-1

            fi